name: build-cachelib-centos-latest
on:
  push:
  pull_request:
    
jobs:
  build-cachelib-centos8-latest:
    name: "CentOS/latest - Build CacheLib with all dependencies"
    runs-on: ubuntu-latest
    # Docker container image name
    container: "ghcr.io/igchor/cachelib-deps:centos8"
    steps:
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === gcc -v ===
          gcc -v
      - name: "checkout sources"
        uses: actions/checkout@v2
      - name: "print workspace"
        run: echo $GITHUB_WORKSPACE
      - name: "build CacheLib using build script"
        run: mkdir build && cd build && cmake ../cachelib -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/opt -DCMAKE_BUILD_TYPE=Debug && make install -j$(nproc)
      - name: "run tests"
        timeout-minutes: 60
        run: cd /opt/tests && $GITHUB_WORKSPACE/run_tests.sh
